In [43]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import sklearn.datasets

#1. Load DataSet
iris_dataset = sklearn.datasets.load_iris()

X = iris_dataset.data
y = iris_dataset.target

#labels
print "Target classes", iris_dataset.target_names
print "Feature names", iris_dataset.feature_names

#actual data
print iris_dataset.data
print iris_dataset.target

Target classes ['setosa' 'versicolor' 'virginica']
Feature names ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 

In [20]:
from sklearn.neighbors import KNeighborsClassifier #classifier
from sklearn.cross_validation import train_test_split #train-test

In [23]:
#2. Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [24]:
print len(X_train) #sanity check to make sure that syntax above is correct
print len(y_train)

105
105


In [27]:
#3. Define model/params
k = 5
knn_classif = KNeighborsClassifier(k)

#4. fit model
knn_classif.fit(X_train, y_train)

#5. score
knn_classif.score(X_test, y_test)

0.97777777777777775

In [34]:
def knn_script(k):
    #3. Define model/params
    knn_classif = KNeighborsClassifier(k)

    #4. fit model
    knn_classif.fit(X_train, y_train)

    #5. score
    return knn_classif.score(X_test, y_test)
    

In [67]:
for i in range(2, 100):
    print "k: %s => %0.3f" % (i, knn_script(i))

scores = [knn_script(i) for i in range(2, 100)]

k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978
k: 10 => 0.978
k: 11 => 0.978
k: 12 => 0.978
k: 13 => 0.978
k: 14 => 0.978
k: 15 => 0.978
k: 16 => 0.978
k: 17 => 0.978
k: 18 => 0.978
k: 19 => 0.978
k: 20 => 0.978
k: 21 => 0.978
k: 22 => 0.978
k: 23 => 0.978
k: 24 => 0.978
k: 25 => 0.978
k: 26 => 0.978
k: 27 => 0.978
k: 28 => 0.978
k: 29 => 0.978
k: 30 => 0.978
k: 31 => 0.978
k: 32 => 0.956
k: 33 => 0.956
k: 34 => 0.956
k: 35 => 0.956
k: 36 => 0.956
k: 37 => 0.956
k: 38 => 0.956
k: 39 => 0.956
k: 40 => 0.956
k: 41 => 0.956
k: 42 => 0.956
k: 43 => 0.956
k: 44 => 0.956
k: 45 => 0.911
k: 46 => 0.933
k: 47 => 0.933
k: 48 => 0.933
k: 49 => 0.911
k: 50 => 0.911
k: 51 => 0.911
k: 52 => 0.911
k: 53 => 0.911
k: 54 => 0.911
k: 55 => 0.911
k: 56 => 0.911
k: 57 => 0.911
k: 58 => 0.911
k: 59 => 0.822
k: 60 => 0.822
k: 61 => 0.844
k: 62 => 0.844
k: 63 => 0.844
k: 64 => 0.844
k: 65 => 0.733
k: 66 => 0.733
k: 67 => 0.711
k: 68 => 0.711
k: 

In [66]:
print plt.scatter(range(2, 100), scores)

### Question:
- How to choose parameters of:
 - Model?
 - Train/Test split?
 - Model Evaluation
  
### Train test split:
- Keep ~70% of data
- Test ~30% of data

K-fold cross validation
- take a dataset
- 75% will be training, 25% will be test
- you can then iterate the training and testing on partitions to gain confidence

e.g. (the 25% test set is a different partition of our ultimate data set each time. k = 4)

25% --- --- ---

--- 25% --- ---

--- --- 25% ---

--- --- --- 25%

In [81]:
arr = np.array(range(1, 100))

from sklearn.cross_validation import KFold

kfolds = KFold(20, 4)

num = 1
for fold in kfolds: # this is showing what folds is doing; taking a partition each iteration
    print "Fold: %s" % num
    
    print "Training indices: ", fold[0]
    print "Test indices: ", fold[1]
    print "\n"
    
    num += 1
    
print fold

TypeError: 'int' object is not iterable

In [ ]:
kfolds = KFold

In [109]:
N_SAMPLES = 100
scores = []

kfolds = 5

X_iris = iris_dataset.data
y_iris = iris_dataset.target

def knn_script(k):
    #3. Define model/params
    knn_classif = KNeighborsClassifier(k)

    #4. fit model
    knn_classif.fit(X_train, y_train)

    #5. score
    return knn_classif.score(X_test, y_test)
    
for i in range(2, N_SAMPLES):
    print "k: %s => %0.3f" % (i, knn_script(i))

scores = [knn_script(i) for i in range(2, N_SAMPLES)]

iris_folds = KFold(len(X_iris), kfolds)

k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978
k: 10 => 0.978
k: 11 => 0.978
k: 12 => 0.978
k: 13 => 0.978
k: 14 => 0.978
k: 15 => 0.978
k: 16 => 0.978
k: 17 => 0.978
k: 18 => 0.978
k: 19 => 0.978
k: 20 => 0.978
k: 21 => 0.978
k: 22 => 0.978
k: 23 => 0.978
k: 24 => 0.978
k: 25 => 0.978
k: 26 => 0.978
k: 27 => 0.978
k: 28 => 0.978
k: 29 => 0.978
k: 30 => 0.978
k: 31 => 0.978
k: 32 => 0.956
k: 33 => 0.956
k: 34 => 0.956
k: 35 => 0.956
k: 36 => 0.956
k: 37 => 0.956
k: 38 => 0.956
k: 39 => 0.956
k: 40 => 0.956
k: 41 => 0.956
k: 42 => 0.956
k: 43 => 0.956
k: 44 => 0.956
k: 45 => 0.911
k: 46 => 0.933
k: 47 => 0.933
k: 48 => 0.933
k: 49 => 0.911
k: 50 => 0.911
k: 51 => 0.911
k: 52 => 0.911
k: 53 => 0.911
k: 54 => 0.911
k: 55 => 0.911
k: 56 => 0.911
k: 57 => 0.911
k: 58 => 0.911
k: 59 => 0.822
k: 60 => 0.822
k: 61 => 0.844
k: 62 => 0.844
k: 63 => 0.844
k: 64 => 0.844
k: 65 => 0.733
k: 66 => 0.733
k: 67 => 0.711
k: 68 => 0.711
k: 

In [120]:
num = 1
kfolds = 5
iris_folds = KFold(len(X_iris), kfolds)

def knn_script2(k):
    #3. Define model/params
    knn_classif = KNeighborsClassifier(k)

    #4. fit model
    knn_classif.fit(X_train, y_train)

    #5. score
    return knn_classif.score(X_test, y_test)

for fold in iris_folds: # this is showing what folds is doing; taking a partition each iteration
    print "Fold: %s" % num
    
    X_train_fold = X_iris[fold[0], :]
    X_test_fold = X_iris[fold[1], :]
    y_train_fold = y_iris[fold[0]]
    y_test_fold = y_iris[fold[1]]
    
    num += 1
    
    for k in range(2, 10):
        print "k: %s => %0.3f" % (k, knn_script(k))
  

Fold: 1
k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978
Fold: 2
k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978
Fold: 3
k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978
Fold: 4
k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978
Fold: 5
k: 2 => 0.978
k: 3 => 0.978
k: 4 => 0.978
k: 5 => 0.978
k: 6 => 0.978
k: 7 => 0.978
k: 8 => 0.978
k: 9 => 0.978


In [102]:
i = 1
for fold in iris_folds:
    #print "TRAINING INDICES: ", fold[0]
    #print "TEST INDICES: ", fold[1]   
    #knn_classif = KNeighborsClassifier(k)
    print "fold: ", i
    X_train_fold = X_iris[fold[0], :]
    X_test_fold = X_iris[fold[1], :]
    y_train_fold = y_iris[fold[0]]
    y_test_fold = y_iris[fold[1]]
    
    #fit model
    knn_classif.fit(X_train_fold, y_train_fold)
    
    #score model
    return "k: %f" % k, knn_classif.score(X_test_fold, y_test_fold)
    
    

In [106]:
for i in range(1, 11):
    print k_fold(i)

('k: 1.000000', 0.83333333333333337)
('k: 2.000000', 0.73333333333333328)
('k: 3.000000', 0.76666666666666672)
('k: 4.000000', 0.76666666666666672)
('k: 5.000000', 0.80000000000000004)
('k: 6.000000', 0.76666666666666672)
('k: 7.000000', 0.80000000000000004)
('k: 8.000000', 0.76666666666666672)
('k: 9.000000', 0.76666666666666672)
('k: 10.000000', 0.76666666666666672)


In [142]:
from sklearn.grid_search import GridSearchCV
#defines, fit and scores models

#minimum of three input for cross validation
# 1. Define the classifier

classifier = KNeighborsClassifier()

# 2. Define the parameter space
parameter_space = {
    'n_neighbors': range(2, 99),
    'weights': ['uniform', 'distance']
}

#3. Define how to validate the model
cross_validator = KFold(len(X_iris), 20)

#GridSearchCV(model, range of parameters, scoring)
gridsearch = GridSearchCV(estimator=classifier,
                          param_grid=parameter_space,
                          cv=cross_validator)

# fit is a common function in SKLearn
gridsearch.fit(X_iris, y_iris)

# underscore item is a 'results' object; it is calculated
# gridsearch.best_score_

print "Best score was %0.3f" % gridsearch.best_score_
print "Best params was: %s" % gridsearch.best_params_

Best score was 0.967
Best params was: {'n_neighbors': 7, 'weights': 'distance'}


In [143]:
for grid_score in gridsearch.grid_scores_:
    print grid_score

mean: 0.94000, std: 0.08270, params: {'n_neighbors': 2, 'weights': 'uniform'}
mean: 0.96000, std: 0.06291, params: {'n_neighbors': 2, 'weights': 'distance'}
mean: 0.96000, std: 0.06291, params: {'n_neighbors': 3, 'weights': 'uniform'}
mean: 0.96000, std: 0.06291, params: {'n_neighbors': 3, 'weights': 'distance'}
mean: 0.94667, std: 0.08162, params: {'n_neighbors': 4, 'weights': 'uniform'}
mean: 0.96000, std: 0.06291, params: {'n_neighbors': 4, 'weights': 'distance'}
mean: 0.96000, std: 0.07317, params: {'n_neighbors': 5, 'weights': 'uniform'}
mean: 0.96000, std: 0.07317, params: {'n_neighbors': 5, 'weights': 'distance'}
mean: 0.94000, std: 0.09096, params: {'n_neighbors': 6, 'weights': 'uniform'}
mean: 0.95333, std: 0.07582, params: {'n_neighbors': 6, 'weights': 'distance'}
mean: 0.96000, std: 0.07317, params: {'n_neighbors': 7, 'weights': 'uniform'}
mean: 0.96667, std: 0.06968, params: {'n_neighbors': 7, 'weights': 'distance'}
mean: 0.94667, std: 0.09069, params: {'n_neighbors': 8, 'w